"""create reference tables

Revision ID: 2038647bf90c
Revises: 
Create Date: 2026-07-17 20:03:06.469991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2038647bf90c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('boxscore_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('abbreviation', sa.String(length=5), nullable=False),
    sa.Column('team_code', sa.String(length=10), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('league_name', sa.String(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('division_name', sa.String(), nullable=True),
    sa.Column('first_year_of_play', sa.String(length=4), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venues',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('azimuth_angle', sa.Numeric(), nullable=True),
    sa.Column('elevation', sa.Integer(), nullable=True),
    sa.Column('time_zone', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('turf_type', sa.String(), nullable=True),
    sa.Column('roof_type', sa.String(), nullable=True),
    sa.Column('left_line', sa.SmallInteger(), nullable=True),
    sa.Column('left_center', sa.SmallInteger(), nullable=True),
    sa.Column('center', sa.SmallInteger(), nullable=True),
    sa.Column('right_center', sa.SmallInteger(), nullable=True),
    sa.Column('right_line', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venues')
    op.drop_table('teams')
    op.drop_table('players')
    # ### end Alembic commands ###
