"""create baserunning tables

Revision ID: 27efe10ec7fe
Revises: f913dea7a2ce
Create Date: 2026-07-17 21:07:21.700157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27efe10ec7fe'
down_revision: Union[str, Sequence[str], None] = 'f913dea7a2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baserunning_events',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('at_bat_index', sa.SmallInteger(), nullable=False),
    sa.Column('event_index', sa.SmallInteger(), nullable=False),
    sa.Column('runner_id', sa.Integer(), nullable=False),
    sa.Column('origin_base', sa.String(length=2), nullable=True),
    sa.Column('start_base', sa.String(length=2), nullable=True),
    sa.Column('end_base', sa.String(length=2), nullable=True),
    sa.Column('out_base', sa.String(length=2), nullable=True),
    sa.Column('is_out', sa.Boolean(), nullable=False),
    sa.Column('out_number', sa.SmallInteger(), nullable=True),
    sa.Column('movement_reason', sa.String(), nullable=True),
    sa.Column('responsible_pitcher_id', sa.Integer(), nullable=True),
    sa.Column('is_scoring_event', sa.Boolean(), nullable=False),
    sa.Column('rbi', sa.Boolean(), nullable=False),
    sa.Column('earned', sa.Boolean(), nullable=False),
    sa.Column('team_unearned', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_id', 'at_bat_index', 'event_index'], ['events.game_id', 'events.at_bat_index', 'events.event_index'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsible_pitcher_id'], ['players.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['runner_id'], ['players.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('game_id', 'at_bat_index', 'event_index', 'runner_id')
    )
    op.create_table('baserunning_event_credits',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('at_bat_index', sa.SmallInteger(), nullable=False),
    sa.Column('event_index', sa.SmallInteger(), nullable=False),
    sa.Column('runner_id', sa.Integer(), nullable=False),
    sa.Column('credit_index', sa.SmallInteger(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('position_code', sa.String(length=2), nullable=False),
    sa.Column('position_name', sa.String(), nullable=False),
    sa.Column('position_abbreviation', sa.String(length=5), nullable=False),
    sa.Column('credit_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['game_id', 'at_bat_index', 'event_index', 'runner_id'], ['baserunning_events.game_id', 'baserunning_events.at_bat_index', 'baserunning_events.event_index', 'baserunning_events.runner_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('game_id', 'at_bat_index', 'event_index', 'runner_id', 'credit_index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('baserunning_event_credits')
    op.drop_table('baserunning_events')
    # ### end Alembic commands ###
