"""create games table

Revision ID: 7b444491e82d
Revises: 2038647bf90c
Create Date: 2026-07-17 20:20:20.324055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b444491e82d'
down_revision: Union[str, Sequence[str], None] = '2038647bf90c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=2), nullable=False),
    sa.Column('game_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('official_date', sa.Date(), nullable=False),
    sa.Column('detailed_state', sa.String(), nullable=False),
    sa.Column('day_night', sa.String(length=10), nullable=True),
    sa.Column('double_header', sa.String(length=1), nullable=False),
    sa.Column('game_number', sa.SmallInteger(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.SmallInteger(), nullable=True),
    sa.Column('away_score', sa.SmallInteger(), nullable=True),
    sa.Column('is_tie', sa.Boolean(), nullable=False),
    sa.Column('scheduled_innings', sa.SmallInteger(), nullable=False),
    sa.Column('series_game_number', sa.SmallInteger(), nullable=True),
    sa.Column('games_in_series', sa.SmallInteger(), nullable=True),
    sa.Column('series_description', sa.String(), nullable=True),
    sa.Column('rescheduled_from', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("double_header IN ('Y','N','S')", name='ck_games_double_header'),
    sa.CheckConstraint("game_type IN ('R','F','D','L','W')", name='ck_games_game_type'),
    sa.CheckConstraint('away_score >= 0', name='ck_games_away_score_nonneg'),
    sa.CheckConstraint('home_score >= 0', name='ck_games_home_score_nonneg'),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
