"""widen baserunning base columns

Revision ID: 9759f768c409
Revises: 66a511287c3a
Create Date: 2026-07-18 22:55:52.645104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9759f768c409'
down_revision: Union[str, Sequence[str], None] = '66a511287c3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('baserunning_events', 'origin_base',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('baserunning_events', 'start_base',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('baserunning_events', 'end_base',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('baserunning_events', 'out_base',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('baserunning_events', 'out_base',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=2),
               existing_nullable=True)
    op.alter_column('baserunning_events', 'end_base',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=2),
               existing_nullable=True)
    op.alter_column('baserunning_events', 'start_base',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=2),
               existing_nullable=True)
    op.alter_column('baserunning_events', 'origin_base',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=2),
               existing_nullable=True)
    # ### end Alembic commands ###
