"""create at_bats and events tables

Revision ID: d5d7a36fa42a
Revises: 6fcae681bf1c
Create Date: 2026-07-17 20:50:13.717068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5d7a36fa42a'
down_revision: Union[str, Sequence[str], None] = '6fcae681bf1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('at_bats',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('at_bat_index', sa.SmallInteger(), nullable=False),
    sa.Column('inning', sa.SmallInteger(), nullable=False),
    sa.Column('half_inning', sa.String(length=3), nullable=False),
    sa.Column('batter_id', sa.Integer(), nullable=False),
    sa.Column('pitcher_id', sa.Integer(), nullable=False),
    sa.Column('bat_side', sa.String(length=1), nullable=False),
    sa.Column('pitch_hand', sa.String(length=1), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('rbi', sa.SmallInteger(), nullable=False),
    sa.Column('is_scoring_play', sa.Boolean(), nullable=False),
    sa.Column('is_out', sa.Boolean(), nullable=False),
    sa.Column('home_score', sa.SmallInteger(), nullable=False),
    sa.Column('away_score', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_at_bat', sa.Boolean(), nullable=False),
    sa.Column('is_hit', sa.Boolean(), nullable=False),
    sa.Column('is_walk', sa.Boolean(), nullable=False),
    sa.Column('is_hit_by_pitch', sa.Boolean(), nullable=False),
    sa.Column('is_strikeout', sa.Boolean(), nullable=False),
    sa.Column('is_sac_fly', sa.Boolean(), nullable=False),
    sa.Column('is_sac_bunt', sa.Boolean(), nullable=False),
    sa.Column('bases', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('bases BETWEEN 0 AND 4', name='ck_at_bats_bases_range'),
    sa.ForeignKeyConstraint(['batter_id'], ['players.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pitcher_id'], ['players.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('game_id', 'at_bat_index')
    )
    op.create_index('ix_at_bats_batter_pitcher', 'at_bats', ['batter_id', 'pitcher_id'], unique=False)
    op.create_index('ix_at_bats_pitcher_batter', 'at_bats', ['pitcher_id', 'batter_id'], unique=False)
    op.create_table('events',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('at_bat_index', sa.SmallInteger(), nullable=False),
    sa.Column('event_index', sa.SmallInteger(), nullable=False),
    sa.Column('global_sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=10), nullable=False),
    sa.Column('is_pitch', sa.Boolean(), nullable=False),
    sa.Column('event_code', sa.String(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('home_score', sa.SmallInteger(), nullable=False),
    sa.Column('away_score', sa.SmallInteger(), nullable=False),
    sa.Column('related_player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id', 'at_bat_index'], ['at_bats.game_id', 'at_bats.at_bat_index'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_player_id'], ['players.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('game_id', 'at_bat_index', 'event_index'),
    sa.UniqueConstraint('game_id', 'global_sequence')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_index('ix_at_bats_pitcher_batter', table_name='at_bats')
    op.drop_index('ix_at_bats_batter_pitcher', table_name='at_bats')
    op.drop_table('at_bats')
    # ### end Alembic commands ###
