"""create pitches and batted_balls tables

Revision ID: f913dea7a2ce
Revises: d5d7a36fa42a
Create Date: 2026-07-17 21:04:31.930144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f913dea7a2ce'
down_revision: Union[str, Sequence[str], None] = 'd5d7a36fa42a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitches',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('at_bat_index', sa.SmallInteger(), nullable=False),
    sa.Column('event_index', sa.SmallInteger(), nullable=False),
    sa.Column('batter_id', sa.Integer(), nullable=False),
    sa.Column('pitcher_id', sa.Integer(), nullable=False),
    sa.Column('pitch_number', sa.SmallInteger(), nullable=False),
    sa.Column('balls', sa.SmallInteger(), nullable=False),
    sa.Column('strikes', sa.SmallInteger(), nullable=False),
    sa.Column('outs', sa.SmallInteger(), nullable=False),
    sa.Column('pitch_type_code', sa.String(length=3), nullable=True),
    sa.Column('pitch_type_description', sa.String(), nullable=True),
    sa.Column('call_code', sa.String(length=3), nullable=False),
    sa.Column('call_description', sa.String(), nullable=False),
    sa.Column('is_strike', sa.Boolean(), nullable=False),
    sa.Column('is_ball', sa.Boolean(), nullable=False),
    sa.Column('is_in_play', sa.Boolean(), nullable=False),
    sa.Column('start_speed', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('end_speed', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('spin_rate', sa.Integer(), nullable=True),
    sa.Column('spin_direction', sa.Integer(), nullable=True),
    sa.Column('break_angle', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('break_length', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('break_vertical', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('break_vertical_induced', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('break_horizontal', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('zone', sa.SmallInteger(), nullable=True),
    sa.Column('type_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('plate_time', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('extension', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('strike_zone_top', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('strike_zone_bottom', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('plate_x', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('plate_z', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('release_pos_x', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('release_pos_y', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('release_pos_z', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('vx0', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('vy0', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('vz0', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('ax', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('ay', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('az', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('pfx_x', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('pfx_z', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('play_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint('balls BETWEEN 0 AND 3', name='ck_pitches_balls_range'),
    sa.CheckConstraint('outs BETWEEN 0 AND 2', name='ck_pitches_outs_range'),
    sa.CheckConstraint('strikes BETWEEN 0 AND 2', name='ck_pitches_strikes_range'),
    sa.ForeignKeyConstraint(['batter_id'], ['players.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['game_id', 'at_bat_index', 'event_index'], ['events.game_id', 'events.at_bat_index', 'events.event_index'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pitcher_id'], ['players.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('game_id', 'at_bat_index', 'event_index'),
    sa.UniqueConstraint('play_id')
    )
    op.create_index('ix_pitches_batter_pitcher', 'pitches', ['batter_id', 'pitcher_id'], unique=False)
    op.create_index('ix_pitches_pitcher_batter', 'pitches', ['pitcher_id', 'batter_id'], unique=False)
    op.create_table('batted_balls',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('at_bat_index', sa.SmallInteger(), nullable=False),
    sa.Column('event_index', sa.SmallInteger(), nullable=False),
    sa.Column('launch_speed', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('launch_angle', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('total_distance', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('trajectory', sa.String(), nullable=True),
    sa.Column('hardness', sa.String(), nullable=True),
    sa.Column('location', sa.String(length=2), nullable=True),
    sa.Column('coord_x', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('coord_y', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['game_id', 'at_bat_index', 'event_index'], ['pitches.game_id', 'pitches.at_bat_index', 'pitches.event_index'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'at_bat_index', 'event_index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('batted_balls')
    op.drop_index('ix_pitches_pitcher_batter', table_name='pitches')
    op.drop_index('ix_pitches_batter_pitcher', table_name='pitches')
    op.drop_table('pitches')
    # ### end Alembic commands ###
